### ISSUE TITLE
Support bundling on MacOS

### ISSUE THREAD

**Issue by joshmgrant** [CodeIntelligenceTesting/cifuzz#399]
I recently tried to run `cifuzz bundle` against some C++ tests and received this message:

```
Creating a bundle is currently only supported on Linux. If you are
interested in using this feature on macOS, please file an issue
```

I would like to see this feature in MacOS. Thanks!

**Comment by MarkusZoppelt** [comment]
Thank you, I have created a ticket in our internal project board.
We will check when to support this feature in the future.

If demand increases, we will prfioritize it more.

**Comment by MarkusZoppelt** [comment]
Since #427 has been merged, we now support bundling on macOS for supported languages (currently only Java).
For C/C++, we cannot support bundling on macOS because the resulting artifact will not be compatible with the remote fuzzing server that only runs Linux.
